# Generated by Django 4.2.2 on 2023-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
                ('Genre', models.CharField(max_length=100)),
                ('Duration_minutes', models.IntegerField()),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
